# Generated by Django 3.2.4 on 2021-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=16),
        ),
    ]
